services:
  scraper:
    build: .
    container_name: db_price_scraper
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
      - USER_AGENT=dbnav
      - DB_PATH=/app/data/price_data.db
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DEBUG=${DEBUG}
    volumes:
      - ./data:/app/data